services:
  postgres:
    image: postgis/postgis:12-2.5
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      target: dev
      args:
        - PYTHON_VERSION=3.9
    depends_on:
      - postgres
    environment:
      - DJANGO_SETTINGS_MODULE=test_vectortiles.settings.dev
    env_file:
      - .env
    volumes:
      - .:/code/src
    ports:
      - "8000:8000"
    command: ./manage.py runserver 0.0.0.0:8000

volumes:
  postgres:
