# Generated by Django 3.1.2 on 2020-10-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('id',)},
        ),
    ]
