# Generated by Django 3.1.6 on 2021-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_auto_20201020_1615"),
    ]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
