# Generated by Django 3.2.17 on 2023-02-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0004_alter_feature_layer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
