# Generated by Django 3.2.17 on 2023-02-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0005_alter_feature_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="layer",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=250),
        ),
        migrations.AddField(
            model_name="layer",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="layer",
            name="max_zoom",
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name="layer",
            name="min_zoom",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="layer",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
