# Generated by Django 3.2.17 on 2023-02-10 08:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0006_auto_20230209_0933"),
    ]

    operations = [
        migrations.CreateModel(
            name="FullDataLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                (
                    "attribution",
                    models.CharField(blank=True, default="", max_length=250),
                ),
                ("description", models.TextField(blank=True)),
                ("min_zoom", models.PositiveSmallIntegerField(default=0)),
                ("max_zoom", models.PositiveSmallIntegerField(default=22)),
            ],
        ),
        migrations.CreateModel(
            name="FullDataFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ("properties", models.JSONField(default=dict)),
                (
                    "layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="test_app.fulldatalayer",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
