# Generated by Django 3.2.17 on 2023-02-10 08:29

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0007_fulldatafeature_fulldatalayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fulldatafeature",
            name="properties",
            field=models.JSONField(
                default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
