# Generated by Django 3.2.17 on 2023-02-10 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0008_alter_fulldatafeature_properties"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fulldatalayer",
            options={"ordering": ("name",)},
        ),
    ]
