# Generated by Django 3.2.17 on 2023-02-13 13:44

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0009_alter_fulldatalayer_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fulldatafeature",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["properties"], name="feature_properties_gin"
            ),
        ),
    ]
