# Generated by Django 3.2.17 on 2023-02-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0010_fulldatafeature_feature_properties_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="fulldatalayer",
            name="include_in_tilejson",
            field=models.BooleanField(default=False),
        ),
    ]
