# Generated by Django 3.2.17 on 2023-02-20 12:53

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0013_alter_fulldatalayer_update_datetime"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fulldatafeature",
            index=models.Index(
                django.db.models.expressions.F("properties__nature"),
                name="properties_nature",
            ),
        ),
    ]
